repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: backend-only flake8
        args:
          - --count
          - --select=E9,F63,F7,F82
          - --show-source
          - --statistics
        language: python
        additional_dependencies:
          - flake8==7.3.0
        files: ^backend/
